### ISSUE TITLE
Axis-core pkg is not working in Webpack 5 when building the code in VS 2022

### ISSUE THREAD

**Issue by slgtech** [FantasticFiasco/axis-js#574]
After installing axis-core NPM, and adding the sample code for testing, the project will not compile. It throws 26 Errors of Module cannot be found for DNS, NET, HTTP, HTTPS, etc.

I believe this is caused by Webpack 5 not automatically including Node.js built-ins. I added the modules referenced in the errors as Externals:{} in the webpack-config.js file and the errors went away. However, now at runtime I am receiving an error "Stream" is undefined.

The NPM seems to have several issues when trying to run in VS2022 react app using webpack and node.js

**Comment by FantasticFiasco** [comment]
You're right, the packages in this repository are designed to be run in the Node.js runtime. Apps built with React normally run in the browser where the API:s available in Node.js aren't available in the browser.

To complicate things since you mention tests. It's not uncommon that test runners run in Node.js, while the application they are testing isn't. I.e. you could probably add these packages as dev dependencies and use them in your tests, but it won't work to add them as dependencies in a project that isn't run in Node.js.

**Comment by FantasticFiasco** [comment]
Closed due to inactivity, please let me know if you want this opened again
